from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class OrchestratorState(Enum):
    IDLE = "idle"
    INIT = "init"
    GENERATING = "generating"
    EVALUATING = "evaluating"
    JUDGING = "judging"
    AGGREGATING = "aggregating"
    DONE = "done"
    ERROR = "error"


@dataclass
class DishProposal:
    id: int
    name: str
    cuisine: str
    price_sgd: float
    description: str
    differentiation: str
    trend_source: str
    name_cn: str = ""
    description_cn: str = ""
    source_refs: list[str] = field(default_factory=list)


@dataclass
class EvaluationResult:
    proposal: DishProposal
    vetoed: bool
    veto_reason: Optional[str]
    cuisine_blue_ocean: float
    trend_heat: float
    hawker_substitutability: float
    total_score: float
    passed: bool
    reasoning: str


@dataclass
class StageTrace:
    """Performance trace for a single pipeline stage."""
    stage: str           # "search" | "summarize" | "generate" | "evaluate" | "feedback"
    elapsed_ms: float
    model_name: str
    input_size_chars: int
    output_size_chars: int
    error: str = ""


@dataclass
class RoundResult:
    cuisine: str
    round_num: int
    proposals_generated: int
    passed_count: int
    rejected_count: int
    locked_total: int
    evaluations: list
    improvement_suggestions: str
    elapsed_seconds: float
    stage_traces: list[StageTrace] = field(default_factory=list)
    ref_map: dict = field(default_factory=dict)
    lineage_results: list = field(default_factory=list)


@dataclass
class CuisineResult:
    cuisine: str
    total_rounds: int
    locked: list
    rounds_history: list


@dataclass
class ExecutiveSummary:
    """Business-readable summary of an entire pipeline run.
    Generated by the Orchestrator after aggregation."""
    overall_pass_rate: str
    total_proposals: int
    total_passed: int
    veto_patterns: list[str]
    low_score_patterns: list[str]
    risk_direction: str
    top_recommendations: list[str]


@dataclass
class FinalOutput:
    timestamp: str
    cuisines: dict
    total_elapsed_seconds: float
    executive_summary: ExecutiveSummary | None = None


@dataclass
class RejectionFeedback:
    """Human feedback: a proposal rejected by the user with reason."""
    proposal_name: str
    proposal_name_cn: str
    cuisine: str
    reason_code: str
    reason_label: str
    custom_note: str = ""
    timestamp: str = ""


@dataclass
class RawCommodity:
    """Direct CSV row — weak structured data from Metabase export."""
    id: int
    name: str
    description: str


@dataclass
class ObservabilityEvent:
    """Unified event for JSON Lines observability. One event = one line.

    Common header fields are serialized at the top level; stage-specific
    data goes into the `payload` dict.  Designed for append-only JSONL
    output so every event in a pipeline run shares a single trace_id.
    """
    trace_id: str
    run_id: str
    session_id: str
    timestamp: str          # ISO 8601 with ms, e.g. "2026-06-02T10:00:11.456"
    cuisine: str
    round_num: int          # 0 = pre-round (search / summarize)
    stage: str              # search | summarize | generate | evaluate | judging | feedback
    event_type: str         # stage_start | stage_end | error | veto | lineage | search_snippet
    status: str             # "success" | "error"
    elapsed_ms: float = 0.0
    model_name: str = ""
    input_size_chars: int = 0
    output_size_chars: int = 0
    error: str = ""
    payload: dict = field(default_factory=dict)


@dataclass
class ProcessedCommodity:
    """Enriched commodity with LLM-generated semantic tags."""
    id: int
    name: str
    description: str
    cuisine_type: str          # Chinese/Japanese/Korean/Thai/Singaporean-Malay/Mexican/Other
